name: Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - name: Move build output
        run: |
          git rm *
          mv _site/* .
          touch .nojekyll
      - name: Commit changes and push
        run: |
          git config --global user.name 'achien'
          git config --global user.email 'achien@users.noreply.github.com'
          git add -A
          git commit -m 'Build site'
          git push -f origin HEAD:gh-pages
